"""multi_org_user_model

Revision ID: 07a87f09eb29
Revises: ebc0e57200ac
Create Date: 2026-05-16 22:28:43.720611

Replace users.org_id + users.role with user_orgs join table.
A user can now belong to multiple orgs simultaneously.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07a87f09eb29"
down_revision: Union[str, Sequence[str], None] = "ebc0e57200ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_orgs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "org_id", name="uq_user_orgs_user_id_org_id"),
    )
    op.drop_constraint(op.f("users_org_id_fkey"), "users", type_="foreignkey")
    op.drop_column("users", "org_id")
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("users", sa.Column("org_id", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f("users_org_id_fkey"), "users", "orgs", ["org_id"], ["id"])
    op.drop_table("user_orgs")
    # ### end Alembic commands ###
