"""org_user_owner

Revision ID: 657cb811832f
Revises: 07a87f09eb29
Create Date: 2026-05-17 10:36:49.284693

Enforce that each user can own at most one org (their personal org).
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "657cb811832f"
down_revision: Union[str, Sequence[str], None] = "07a87f09eb29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("uq_user_orgs_owner_per_user", "user_orgs", ["user_id"], unique=True, postgresql_where="role = 'owner'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_user_orgs_owner_per_user", table_name="user_orgs", postgresql_where="role = 'owner'")
    # ### end Alembic commands ###
