"""add_org_billing

Revision ID: f3961ade6392
Revises: bbee977b5454
Create Date: 2026-05-17 11:48:31.102906

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3961ade6392"
down_revision: Union[str, Sequence[str], None] = "bbee977b5454"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org_billing",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("plan", sa.String(), nullable=False),
        sa.Column("seat_count", sa.Integer(), nullable=False),
        sa.Column("reviews_used_this_month", sa.Integer(), nullable=False),
        sa.Column("quota_reset_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id"),
        sa.CheckConstraint("seat_count >= 1", name="ck_org_billing_seat_count_positive"),
        sa.CheckConstraint("reviews_used_this_month >= 0", name="ck_org_billing_reviews_used_non_negative"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("org_billing")
    # ### end Alembic commands ###
